### ISSUE TITLE
Frequency of update of data in Home Assistant too Low

### ISSUE THREAD

**Issue by TilerDon** [mmillmor/geo_home#13]
I hope I'm doing this correctly - First time I've raised an issue.

I'm trying to eliminate the need to have the Trio IHD close by in order to see changes in Electricity Usage as an when they happen.

I have nodeRed running inside Home Assistant and have a dashboard that monitors and controls all my energy usage. I only recently found the Geo Home integration and see that it provides me with all the information I need except....

The data in Home Assistant only appears to be updated every 4 or 5 minutes. The Geo Apps themselves update almost instantaneously with The IHD - even when the app is being run in an emulator on a PC.

Cost Data seems to be updated even less frequently but I'm not too worried about that. I just want to be able to see what impact on immediate usage, turning an appliance on or off has.

Hope this explains the problem and that a resolution is forthcoming

**Comment by mmillmor** [comment]
The data is updated every 120 seconds at the moment (including the cost data). I do have a concern that, unlike the app, this is running 24x7. So while the app may update faster, you only keep the app open for a shorter time, so the overall api calls per day may be lower. If everyone starts hitting the server very frequently due to this integration polling too rapidly, there is a danger that Geo Home shut down api access completely. This limit is an attempt to be responsible about the frequency for the sake of everyone.
