### ISSUE TITLE
Energy Dashboard Configuration - Typo?

### ISSUE THREAD

**Issue by mprowe** [mmillmor/geo_home#14]
Should this be: **sensor.electricity_price_per_kwh**?

![GeoHome](https://user-images.githubusercontent.com/14279344/216704730-1cb0e19d-9b18-49af-9434-3051e264020d.png)

Regards, Martin

**Comment by mmillmor** [comment]
No, I think this is correct. Note that it is used with "Use an entity track the total costs", not "Use an entity with the current price". You are correct in picking the price per kwh if it were for the current price, but I think it is more accurate to track the cost incurred today from the info from the API because that when you have fluctuating rates it will keep cost and usage exactly in sync, whereas if we try to do it locally, we likey won't change cost per kwh and usage at exactly the right time, so it will be less accurate.
